
stages:
  - build

nginx:
  stage: build
  image:
    # We recommend using the CERN version of the Kaniko image: gitlab-registry.cern.ch/ci-tools/docker-image-builder
    name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
    entrypoint: [""]
  script:
    - |
        if [[ "$CI_COMMIT_BRANCH" == "v"* ]] ; then
          export DATE=`date -u +%Y.%m.%dT%H-%M-%SZ`
          export TAG=${TAG:-"RELEASE".$DATE}
        else
          export TAG=$CI_COMMIT_SHORT_SHA
        fi
    - wget --no-check-certificate https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 -O /yq && chmod +x /yq
    - export softwareVersions=$CI_PROJECT_DIR/images/softwareVersions
    - export nginxVersion=`/yq e .nginx $softwareVersions`
      # This is not the common Authentication config, unknown reason why common config fails
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
      # Image builder for nginx
    - /kaniko/executor --context "$CI_PROJECT_DIR/images/nginx" --dockerfile "$CI_PROJECT_DIR/images/nginx/Dockerfile"
      --destination ${CI_REGISTRY_IMAGE}/nginx:${CI_COMMIT_BRANCH}-${TAG}
      --build-arg NGINX_VERSION=\$nginxVersion;
    - echo "Nginx image pushed to ${CI_REGISTRY_IMAGE}/nginx:${CI_COMMIT_BRANCH}-${TAG}"
sitebuilder:
  stage: build
  image:
    # We recommend using the CERN version of the Kaniko image: gitlab-registry.cern.ch/ci-tools/docker-image-builder
    name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
    entrypoint: [""]
  script:
    - |
        if [[ "$CI_COMMIT_BRANCH" == "v"* ]]; then
          export DATE=`date -u +%Y.%m.%dT%H-%M-%SZ`
          export TAG=${TAG:-"RELEASE".$DATE}
        else
          export TAG=$CI_COMMIT_SHORT_SHA
        fi
    - wget --no-check-certificate https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 -O /yq && chmod +x /yq
    - export softwareVersions=$CI_PROJECT_DIR/images/softwareVersions
    - export phpVersion=`/yq e .php $softwareVersions`
    - export composerVersion=`/yq e .composer $softwareVersions`
    - export drushVersion=`/yq e .drush $softwareVersions`
      # This is not the common Authentication config, unknown reason why common config fails
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
      # Image builder for Site-Builder
    - /kaniko/executor --context "$CI_PROJECT_DIR/images" --dockerfile "$CI_PROJECT_DIR/images/Dockerfile"
      --destination ${CI_REGISTRY_IMAGE}/site-builder:${CI_COMMIT_BRANCH}-${TAG}
      --build-arg PHP_VERSION=$phpVersion --build-arg COMPOSER_VERSION=$composerVersion --build-arg DRUSH_VERSION=$drushVersion;
    - echo "SiteBuilder image pushed to ${CI_REGISTRY_IMAGE}/site-builder:${CI_COMMIT_BRANCH}-${TAG}"

