stages:
  - nginx
  - sitebuilder

build-nginx:
  stage: nginx
  image:
    # We recommend using the CERN version of the Kaniko image: gitlab-registry.cern.ch/ci-tools/docker-image-builder
    name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
    entrypoint: [""]
  script:
    - |
      case "$CI_COMMIT_BRANCH" in
        v*) export DATE=$(date -u +%Y.%m.%dT%H-%M-%SZ); export TAG="RELEASE"-${DATE}; echo "TAG=$TAG" >> build.env ;;
        *) export TAG=$CI_COMMIT_SHORT_SHA ;;
      esac
    - wget --no-check-certificate https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 -O /yq && chmod +x /yq
    - export softwareVersions=$CI_PROJECT_DIR/images/softwareVersions
    - export nginxVersion=`/yq e .nginx $softwareVersions`
      # This is not the common Authentication config, unknown reason why common config fails
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
      # Image builder for nginx
    - /kaniko/executor --context "$CI_PROJECT_DIR/images/nginx" --dockerfile "$CI_PROJECT_DIR/images/nginx/Dockerfile"
      --destination ${CI_REGISTRY_IMAGE}/nginx:${CI_COMMIT_BRANCH}-${TAG}
      --build-arg NGINX_VERSION=\$nginxVersion;
    - echo "Nginx image pushed to ${CI_REGISTRY_IMAGE}/nginx:${CI_COMMIT_BRANCH}-${TAG}"
  artifacts:
    reports:
      dotenv: build.env

build-sitebuilder:
  stage: sitebuilder
  needs: [build-nginx]
  image:
    # We recommend using the CERN version of the Kaniko image: gitlab-registry.cern.ch/ci-tools/docker-image-builder
    name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
    entrypoint: [""]
  script:
    # Using POSIX string check since "[[]]" failed
    - echo $DATE
    - |
      case "$CI_COMMIT_BRANCH" in
        v*) echo $TAG;;
        *) export TAG=$CI_COMMIT_SHORT_SHA ;;
      esac
    - wget --no-check-certificate https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 -O /yq && chmod +x /yq
    - export softwareVersions=$CI_PROJECT_DIR/images/softwareVersions
    - export phpVersion=`/yq e .php $softwareVersions`
    - export composerVersion=`/yq e .composer $softwareVersions`
      # This is not the common Authentication config, unknown reason why common config fails
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
      # Image builder for Site-Builder
    - /kaniko/executor --context "$CI_PROJECT_DIR/images" --dockerfile "$CI_PROJECT_DIR/images/Dockerfile"
      --destination ${CI_REGISTRY_IMAGE}/site-builder:${CI_COMMIT_BRANCH}-${TAG}
      --build-arg PHP_VERSION=$phpVersion --build-arg COMPOSER_VERSION=$composerVersion;
    - echo "SiteBuilder image pushed to ${CI_REGISTRY_IMAGE}/site-builder:${CI_COMMIT_BRANCH}-${TAG}"

