apiVersion: drupal.webservices.cern.ch/v1alpha1
kind: DrupalSite
metadata:
  name: "${SITENAME}"
  namespace: "${NAMESPACE}"
  labels:
     drupal.cern.ch/cdd-ci: "${PIPELINE_ID}"
spec:
  configuration:
    databaseClass: standard
    diskSize: "${DISK_SIZE}"
    qosClass: standard
    cloneFrom: "${CLONE_FROM}"
  siteUrl:
  - "${SITENAME}.webtest.cern.ch"
  version:
    name: "${VERSION_NAME}"
    releaseSpec: "${VERSION_SPEC}"
